version: '3'

services:
  mongodb:
    image: mongo
    container_name: my-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-python-api
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: "mongodb://root:example@mongodb:27017/mydatabase"
